# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[(b'1', b'Todo'), (b'2', b'Doing'), (b'3', b'Done')], max_length=5),
        ),
    ]
